### ISSUE TITLE
Tooltip tail

### ISSUE THREAD

**Issue by byjake** [DesignQuench/thirst#8]
Need them tails for the tooltips

**Comment by hunterboerner** [comment]
Tail?

**Comment by byjake** [comment]
http://lmgtfy.com/?q=tooltip+arrow

**Comment by byjake** [comment]
I'm currently fixing this one, though.

**Comment by byjake** [comment]
Tooltip arrows are now added as in commit b968b9870041545ef1fa077eb876cff40dfd3d6f which therefore resolves Issue #8.
